language: objective-c
osx_image: xcode8

before_install:
  - sudo gem install xcpretty
  
script:
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker iOS" -destination "platform=iOS Simulator,name=iPhone 6"  | xcpretty -c && exit ${PIPESTATUS[0]}
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker OS X" | xcpretty -c && exit ${PIPESTATUS[0]}

after_success:
- bash <(curl -s https://codecov.io/bash) 

after_failure:
  - tail -n 500 build.log
