branches:
  only:
  - master

language: objective-c
osx_image: xcode8

script:
- xcodebuild test -project ByteBackpacker.xcodeproj -scheme "ByteBackpacker OS X"

after_success:
- bash <(curl -s https://codecov.io/bash)  -J 'ByteBackpacker'
